Make aodh tempest tests work with Python3
With Python3 aodh tests fails with below Error,
this patch fixes it:-

TypeError: a bytes-like object is required, not 'str'

Change-Id: I447c384a280e6225f3617a251314b307855d6025
Closes-Bug: #1809802